### ISSUE TITLE
Needs setuptools as a dependency

### ISSUE THREAD

**Issue by dstathis** [timothycrosley/isort#1095]
When running isort I got this error

```Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/.local/lib/python3.6/site-packages/isort/__main__.py", line 7, in <module>
    from isort.main import main  # noqa: E402 isort:skip
  File "/home/runner/.local/lib/python3.6/site-packages/isort/main.py", line 29, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'
##[error]Process completed with exit code 1.
```

Installing setuptools fixed the issue.

**Comment by timothycrosley** [comment]
Thanks for reporting!
This is fixed on develop and will make it's way into the 5.0.0 release of isort.
