### ISSUE TITLE
stumbles over known_first_party in pyproject.toml

### ISSUE THREAD

**Issue by jendrikseipp** [timothycrosley/isort#1117]
I'm using isort version 4.3.21.

When I add `known_first_party = foo` to the [tool.isort] section in pyproject.toml, I get the following error: 
```
Traceback (most recent call last):
  File "/home/jendrik/.local/pipx/venvs/isort[pyproject]/lib/python3.6/site-packages/toml/decoder.py", line 456, in loads
    multibackslash)
  File "/home/jendrik/.local/pipx/venvs/isort[pyproject]/lib/python3.6/site-packages/toml/decoder.py", line 725, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/jendrik/.local/pipx/venvs/isort[pyproject]/lib/python3.6/site-packages/toml/decoder.py", line 840, in load_value
    v = int(v, 0)
ValueError: invalid literal for int() with base 0: 'foo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jendrik/.local/bin/isort", line 8, in <module>
    sys.exit(main())
  File "/home/jendrik/.local/pipx/venvs/isort[pyproject]/lib/python3.6/site-packages/isort/main.py", line 351, in main
    config = from_path(arguments.get('settings_path', '') or os.path.abspath(file_names[0]) or os.getcwd()).copy()
  File "/home/jendrik/.local/pipx/venvs/isort[pyproject]/lib/python3.6/site-packages/isort/settings.py", line 177, in from_path
    _update_settings_with_config(path, 'pyproject.toml', [], ('tool.isort', ), computed_settings)
  File "/home/jendrik/.local/pipx/venvs/isort[pyproject]/lib/python3.6/site-packages/isort/settings.py", line 207, in _update_settings_with_config
    _update_with_config_file(editor_config_file, sections, computed_settings)
  File "/home/jendrik/.local/pipx/venvs/isort[pyproject]/lib/python3.6/site-packages/isort/settings.py", line 212, in _update_with_config_file
    settings = _get_config_data(file_path, sections).copy()
  File "/home/jendrik/.local/pipx/venvs/isort[pyproject]/lib/python3.6/site-packages/isort/settings.py", line 288, in _get_config_data
    config = toml.load(config_file)
  File "/home/jendrik/.local/pipx/venvs/isort[pyproject]/lib/python3.6/site-packages/toml/decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "/home/jendrik/.local/pipx/venvs/isort[pyproject]/lib/python3.6/site-packages/toml/decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: invalid literal for int() with base 0: 'foo' (line 27 column 1 char 526)
```

**Comment by timothycrosley** [comment]
This is fixed in develop, and will make it's way into the soon to be released 5.0.0 version. Though note, either way quotes are required around `foo`
