### ISSUE TITLE
isort raises ValueError unless values in [tool.isort] section in pyproject.toml are in quotes

### ISSUE THREAD

**Issue by erikr** [timothycrosley/isort#1182]
## Description
Values in `[tool.isort]` section in `pyproject.toml` require quotes.

If values are not in quotes, a ValueError is raised. See more below.

## Expected Behavior
Values in `[tool.isort]` section in `pyproject.toml` should not require quotes. The syntax should be directly copy-pastable from one's `.isort.cfg` into one's `pyproject.toml`.

## To Reproduce
1. `test.py` with only a single import statement:
```
import pandas as pd
```
2. `pyproject.toml`:
```
[tool.isort]
length_sort = "True"
```
3. Run `isort`:
```
$ isort test.py
Fixing /home/USER/test.py
```
4. Remove quotes from value in `pyproject.toml`:
```
[tool.isort]
length_sort = True
```
5. Run `isort` again:
```
$ isort test.py
Traceback (most recent call last):
  File "/home/USER/anaconda3/envs/py37/lib/python3.7/site-packages/toml/decoder.py", line 456, in loads
    multibackslash)
  File "/home/USER/anaconda3/envs/py37/lib/python3.7/site-packages/toml/decoder.py", line 725, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/USER/anaconda3/envs/py37/lib/python3.7/site-packages/toml/decoder.py", line 832, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/anaconda3/envs/py37/bin/isort", line 11, in <module>
    sys.exit(main())
  File "/home/USER/anaconda3/envs/py37/lib/python3.7/site-packages/isort/main.py", line 351, in main
    config = from_path(arguments.get('settings_path', '') or os.path.abspath(file_names[0]) or os.getcwd()).copy()
  File "/home/USER/anaconda3/envs/py37/lib/python3.7/site-packages/isort/settings.py", line 177, in from_path
    _update_settings_with_config(path, 'pyproject.toml', [], ('tool.isort', ), computed_settings)
  File "/home/USER/anaconda3/envs/py37/lib/python3.7/site-packages/isort/settings.py", line 207, in _update_settings_with_config
    _update_with_config_file(editor_config_file, sections, computed_settings)
  File "/home/USER/anaconda3/envs/py37/lib/python3.7/site-packages/isort/settings.py", line 212, in _update_with_config_file
    settings = _get_config_data(file_path, sections).copy()
  File "/home/USER/anaconda3/envs/py37/lib/python3.7/site-packages/isort/settings.py", line 288, in _get_config_data
    config = toml.load(config_file)
  File "/home/USER/anaconda3/envs/py37/lib/python3.7/site-packages/toml/decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "/home/USER/anaconda3/envs/py37/lib/python3.7/site-packages/toml/decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 2 column 1 char 13)
```

## Package versions

isort 4.3.21
setuptools 46.1.3
python 3.7.7
not sure what other packages should be listed here

**Comment by bsolomon1124** [comment]
I believe that [toml wants lowercase `true`](https://github.com/toml-lang/toml#example).

**Comment by erikr** [comment]
Thanks @bsolomon1124! Issue resolved.
