### ISSUE TITLE
New --skip behavior conflicts with VSCode Python extension "organize on save"

### ISSUE THREAD

**Issue by matheusmb** [timothycrosley/isort#1183]
I found the issue #920 in which describes that isort no longer skips items directly passed in, even if it's being asked to by setup.cfg or --skip arg. 

Therefore, when using VSCode Python's extension with organize on save enabled (`codeActionsOnSave.source.organizeImports: true`) the files won't be skipped as the extension directly calls isort with the saved filename.

I want to skip all \_\_init\_\_.py files and the solutions that I found are either adding the `isort:skip_file` at the file docstring or using isort version 4.3.10 or below.

Could isort have an option to explicitly check the skip list even when the filename is directly passed in?

**Comment by timothycrosley** [comment]
isort does now have this (--filter-files)

**Comment by Minokori** [comment]
hello, I met the same question on using the isort plugin in vscode though I've set the CLI args in vscode plugins. My args are set like below:

 ![Image](https://github.com/user-attachments/assets/1ff1b804-ee73-4d89-8656-03623e76382c)

And I've wrote an isort command at first line of my `__init__.py` file:

![Image](https://github.com/user-attachments/assets/b9900c38-5f5f-4596-9ca9-3c9322fe569f)

Vscode isort plugin still deleted unused import in my `__init__.py` file, and I found Errors in isort plugin's output:

```
2024-12-06 14:26:45.274 [info] d:\Python39\python.exe -m isort - --lines-after-imports=2 --skip-glob=['**/__init__.py'] --filter-files --check --filename e:\Lenovo\Documents\Onedrive\I2A\RNN\utils\__init__.py
2024-12-06 14:26:45.274 [info] [Trace - 14:26:45] Received notification 'window/logMessage'.
2024-12-06 14:26:45.274 [info] CWD Linter: E:\Lenovo\Documents\Onedrive\I2A\RNN
2024-12-06 14:26:45.279 [info] [Trace - 14:26:45] Received notification 'window/logMessage'.
2024-12-06 14:26:45.279 [info] [Warn  - 14:26:45] Traceback (most recent call last):
  File "d:\Python39\lib\site-packages\isort\api.py", line 210, in sort_stream
    changed = core.process(
  File "d:\Python39\lib\site-packages\isort\core.py", line 162, in process
    raise FileSkipComment("Passed in content")
isort.exceptions.FileSkipComment: Passed in content contains a file skip comment and was skipped.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Lenovo\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_server.py", line 642, in _run_tool_on_document
    result = utils.run_module(
  File "c:\Users\Lenovo\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_utils.py", line 147, in run_module
    return _run_module(module, argv, use_stdin, source)
  File "c:\Users\Lenovo\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_utils.py", line 132, in _run_module
    runpy.run_module(module, run_name="__main__")
  File "d:\Python39\lib\runpy.py", line 213, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "d:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\Python39\lib\site-packages\isort\__main__.py", line 3, in <module>
    main()
  File "d:\Python39\lib\site-packages\isort\main.py", line 1134, in main
    incorrectly_sorted = not api.check_stream(
  File "d:\Python39\lib\site-packages\isort\api.py", line 264, in check_stream
    changed: bool = sort_stream(
  File "d:\Python39\lib\site-packages\isort\api.py", line 218, in sort_stream
    raise FileSkipComment(content_source)
isort.exceptions.FileSkipComment: e:\Lenovo\Documents\Onedrive\I2A\RNN\utils\__init__.py contains a file skip comment and was skipped.
```

How could I make isort plugin ignore `__init__.py` files? I'm using isort `5.13.2`.
