### ISSUE TITLE
python setup.py isort fails with TypeError: __init__() got an unexpected keyword argument 'check'

### ISSUE THREAD

**Issue by msapiro** [timothycrosley/isort#1258]
This is new in 5.0.2. There was no issue in 4.3.21.

Originally I was seeing TypeError: __init__() got an unexpected keyword argument 'use_paranthesis'. This was due to the tox.ini file (in 3 different projects) containing `use_parentheses=True` in the `isort` section. I have fixed those and I am now seeing TypeError: __init__() got an unexpected keyword argument 'check' as in:
```
lint run-test: commands[1] | python setup.py isort
running isort
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    "django-debug-toolbar",
  File "/var/MM/3/fix_300/hyperkitty/.tox/lint/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/var/MM/3/fix_300/hyperkitty/.eggs/isort-5.0.2-py3.7.egg/isort/setuptools_commands.py", line 58, in run
    if not api.check_file(python_file, **arguments):
  File "/var/MM/3/fix_300/hyperkitty/.eggs/isort-5.0.2-py3.7.egg/isort/api.py", line 230, in check_file
    **config_kwargs,
  File "/var/MM/3/fix_300/hyperkitty/.eggs/isort-5.0.2-py3.7.egg/isort/api.py", line 166, in check_stream
    config = _config(path=file_path, config=config, **config_kwargs)
  File "/var/MM/3/fix_300/hyperkitty/.eggs/isort-5.0.2-py3.7.egg/isort/api.py", line 329, in _config
    config = Config(**config_kwargs)
  File "/var/MM/3/fix_300/hyperkitty/.eggs/isort-5.0.2-py3.7.egg/isort/settings.py", line 309, in __init__
    super().__init__(sources=tuple(sources), **combined_config)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'check'

```

**Comment by msapiro** [comment]
Nevermind...

The misspelled `use_paranthesis` is in my own tox.ini.

**Comment by msapiro** [comment]
I have edited the title and description to reflect a new issue. Namely, I corrected the misspelling of `parentheses` in the three offending tox.ini files and now I see the TypeError: __init__() got an unexpected keyword argument 'check' exception. This time, I don't see where that's coming from so I'm reopening this.

**Comment by timothycrosley** [comment]
@msapiro  is it possible you have something along the lines of `check=True` in your configuration? isort does have a check command line option: https://timothycrosley.github.io/isort/docs/configuration/options/#check and equivalent check API function: https://timothycrosley.github.io/isort/reference/isort/api/#check_code_string. But these have never been supported via config. However, like you mentioned unsupported options used to fail silently.

**Comment by msapiro** [comment]
@timothycrosley Cool! Thank you.

**Comment by timothycrosley** [comment]
Happy to help! Closing as patch released was just published :)
