### ISSUE TITLE
Crasher on simple file

### ISSUE THREAD

**Issue by spookylukey** [timothycrosley/isort#312]
Using tip of develop branch, commit 71f4ce50da091b13d3a0b3e43ab4dfcca336857f,

on the following minimal test case:

    import logging
    # Foo
    import os

I'm getting the following error:

    Traceback (most recent call last):
      File "/home/luke/.virtualenvs/wolfandbadger/bin/isort", line 9, in <module>
        load_entry_point('isort==4.0.0', 'console_scripts', 'isort')()
      File "/home/luke/.virtualenvs/wolfandbadger/src/isort/isort/main.py", line 222, in main
        sort_attempt = SortImports(file_name, **arguments)
      File "/home/luke/.virtualenvs/wolfandbadger/src/isort/isort/isort.py", line 134, in __init__
        self._parse()
      File "/home/luke/.virtualenvs/wolfandbadger/src/isort/isort/isort.py", line 812, in _parse
        self.comments['above']['from'].setdefault(module, []).insert(0, self.out_lines.pop(-1))
    IndexError: pop from empty list

This doesn't happen with 4.0.0

**Comment by timothycrosley** [comment]
@spookylukey 

Thanks for reporting this issue! I've pinpointed what was causing it to occur and fixed it here: https://github.com/timothycrosley/isort/pull/313. The development branch should now be stable, so I'm closing this issue.

Thanks!

~Timothy
