### ISSUE TITLE
Raises an error when calling from subprocess.call

### ISSUE THREAD

**Issue by 990px** [timothycrosley/isort#396]
>>> from subprocess import call
    >>> call('isort')  # works
    >>> call('isort -c')  # does not work
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/subprocess.py", line 522, in call
        return Popen(*popenargs, **kwargs).wait()
      File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

**Comment by bootandy** [comment]
https://docs.python.org/2/library/subprocess.html#using-the-subprocess-module

Did you mean to call this?

> call(['isort', "-c"])
Skipped 1 files
0

**Comment by 990px** [comment]
My bad, I should add `shell=True` argument.
