### ISSUE TITLE
Can't select option y/n/q when running isort -rc after latest update

### ISSUE THREAD

**Issue by jaimesanz** [timothycrosley/isort#546]
I just updated to v4.2.9, and I'm getting the following error after running `isort -rc`:

    ...
    Apply suggested changes to '/home/jsanz/Documents/manungo2/manungo2/orders/views.py' [y/n/q]?y
    Traceback (most recent call last):
        File "/home/jsanz/Documents/manungo2/venv/bin/isort", line 11, in <module> sys.exit(main())
        File "/home/jsanz/Documents/manungo2/venv/local/lib/python2.7/site-packages/isort/main.py", line 275, in main
            sort_attempt = SortImports(file_name, **arguments)
        File "/home/jsanz/Documents/manungo2/venv/local/lib/python2.7/site-packages/isort/isort.py", line 198, in __init__
            answer = input("Apply suggested changes to '{0}' [y/n/q]?".format(self.file_path)).lower()
        File "<string>", line 1, in <module>
            NameError: name 'y' is not defined

However, if I input ``"y"`` instead of ``y``, it works.

EDIT: this also happens on v4.2.8, but **not** on v4.2.5. I'm using python 2.7

**Comment by timothycrosley** [comment]
Thanks for reporting this major issue!

I have pushed out a hotfix release: `4.2.11` that resolves it.

Thanks!

~Timothy
