### ISSUE TITLE
encoding error in windows

### ISSUE THREAD

**Issue by insight1111** [timothycrosley/isort#581]
OS: windows10 64bit(locale is japanese)
python: 3.6.2(installed by chocolatey)

install isort `pip install isort`. and make test project folder and run isort.
then I get below error messages.

```
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\isort.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\isort\main.py", line 264, in main
    config = from_path(os.path.abspath(file_names[0]) or os.getcwd()).copy()
  File "c:\python36\lib\site-packages\isort\settings.py", line 139, in from_path
    _update_settings_with_config(path, '.editorconfig', '~/.editorconfig', ('*', '*.py', '**.py'), computed_settings)
  File "c:\python36\lib\site-packages\isort\settings.py", line 163, in _update_settings_with_config
    _update_with_config_file(editor_config_file, sections, computed_settings)
  File "c:\python36\lib\site-packages\isort\settings.py", line 167, in _update_with_config_file
    settings = _get_config_data(file_path, sections).copy()
  File "c:\python36\lib\site-packages\isort\settings.py", line 222, in _get_config_data
    line = config_file.readline()
UnicodeDecodeError: 'cp932' codec can't decode byte 0x99 in position 73: illegal multibyte sequence
```

how to fix it? Please.

on the other hand,in bash on windows, isort works correctly.

**Comment by jasonbrackman** [comment]
@insight1111 I know its been awhile -- but I'm wondering if you could provide any additional details.  I attempted to repro the issue and did the following:

1. downloaded a virtual box iso of Windows10 and switched the locale to Japanese (and restarted)
2. Installed python (from python.org)
3. Pip installed isort
4. created a single test.py with a series of import statements
5. created an .isort.cfg in the same directory and even used some Japanese characters.
6. ran python -m isort test.py from the cmd prompt and I did not hit the assert

**Comment by timothycrosley** [comment]
Closing this until better reproduction steps are added
