### ISSUE TITLE
`python -m isort` ImportError Failure in python2

### ISSUE THREAD

**Issue by DavidMuller** [timothycrosley/isort#616]
`python -m isort` runs fine in python3...

```
[3-5-sandbox]dmuller:~> python -V
Python 3.5.2

[3-5-sandbox]dmuller:~> pip freeze | grep isort
isort==4.2.15

[3-5-sandbox]dmuller:~> python -m isort tmp.py --check-only 

[3-5-sandbox]dmuller:~>
```

but fails in a python 2 environment:

```
[2-7-sandbox]dmuller:~> python -V
Python 2.7.10

[2-7-sandbox]dmuller:~> pip freeze | grep isort
isort==4.2.15

[2-7-sandbox]dmuller:~> python -m isort
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/david/.virtualenvs/2-7-sandbox/lib/python2.7/site-packages/isort/__main__.py", line 1, in <module>
    from isort.main import main
ImportError: No module named main

[2-7-sandbox]dmuller:~> 
```

Related pull request (which I assume was only a fix for the `python -m` invocation in python 3?): https://github.com/timothycrosley/isort/pull/461

Any idea what's going on here?  

Thank you for all the hard work on this package!

**Comment by asottile** [comment]
Here's a fix: #621
