### ISSUE TITLE
TypeError: '>' not supported between instances of 'int' and 'str' when -wl option is used

### ISSUE THREAD

**Issue by dangitall** [timothycrosley/isort#741]
With this as the contents of file.py:

```
from longimportedmodule.modulepath import (first_thing_to_get,
                                           second_thing_to_get)
```

Running `isort -wl 79 file.py` with isort 4.3.4 on python 3.6.4 I get this stack trace:

```
Traceback (most recent call last):
  File "/Users/dan/.pyenv/versions/dpw3/bin/isort", line 11, in <module>
    sys.exit(main())
  File "/Users/dan/.pyenv/versions/3.6.4/envs/dpw3/lib/python3.6/site-packages/isort/main.py", line 343, in main
    sort_attempt = SortImports(file_name, **arguments)
  File "/Users/dan/.pyenv/versions/3.6.4/envs/dpw3/lib/python3.6/site-packages/isort/isort.py", line 163, in __init__
    self._add_formatted_imports()
  File "/Users/dan/.pyenv/versions/3.6.4/envs/dpw3/lib/python3.6/site-packages/isort/isort.py", line 573, in _add_formatted_imports
    self._add_from_imports(from_modules, section, section_output, sort_ignore_case)
  File "/Users/dan/.pyenv/versions/3.6.4/envs/dpw3/lib/python3.6/site-packages/isort/isort.py", line 502, in _add_from_imports
    import_statement = self._multi_line_reformat(import_start, from_import_section, comments)
  File "/Users/dan/.pyenv/versions/3.6.4/envs/dpw3/lib/python3.6/site-packages/isort/isort.py", line 519, in _multi_line_reformat
    dynamic_indent, indent, line_length, comments)
  File "/Users/dan/.pyenv/versions/3.6.4/envs/dpw3/lib/python3.6/site-packages/isort/isort.py", line 662, in _output_grid
    if len(next_statement.split(self.line_separator)[-1]) + 1 > line_length:
TypeError: '>' not supported between instances of 'int' and 'str'
```

**Comment by paranoidi** [comment]
Consider this verified, I'm having the same issue.

**Comment by timothycrosley** [comment]
Unable to reproduce on latest develop branch, let me know if you are able to reproduce after today's release and I will reopen. Thank you!

**Comment by patrickdepinguin** [comment]
I see the same on isort 4.3.21 using Python 3.6, not with Python 2.7.
/tmp/api.py:
```
from aaaaaaaaa.bbb.cccc import (xxxxxxxxxxxxxxxxxxxxxx, yyyyyyyyyyyyyyyyyyyyyyyyyyy)
```

python3 venv/bin/isort --wrap-length 160 /tmp/api.py
```
Traceback (most recent call last):
  File "venv/bin/isort", line 8, in <module>
    sys.exit(main())
  File "venv/lib/python3.6/site-packages/isort/main.py", line 379, in main
    for sort_attempt in attempt_iterator:
  File "venv/lib/python3.6/site-packages/isort/main.py", line 377, in <genexpr>
    attempt_iterator = (sort_imports(file_name, **arguments) for file_name in file_names)
  File "venv/lib/python3.6/site-packages/isort/main.py", line 88, in sort_imports
    result = SortImports(file_name, **arguments)
  File "venv/lib/python3.6/site-packages/isort/isort.py", line 207, in __init__
    self._add_formatted_imports()
  File "venv/lib/python3.6/site-packages/isort/isort.py", line 606, in _add_formatted_imports
    self._add_from_imports(from_modules, section, section_output, sort_ignore_case)
  File "venv/lib/python3.6/site-packages/isort/isort.py", line 526, in _add_from_imports
    import_statement = self._multi_line_reformat(import_start, from_import_section, comments)
  File "venv/lib/python3.6/site-packages/isort/isort.py", line 552, in _multi_line_reformat
    dynamic_indent, indent, line_length, comments)
  File "venv/lib/python3.6/site-packages/isort/isort.py", line 705, in _output_grid
    if len(next_statement.split(self.line_separator)[-1]) + 1 > line_length:
TypeError: '>' not supported between instances of 'int' and 'str'
```

**Comment by patrickdepinguin** [comment]
Printing of 'line_length' and type(line_length) indeed shows that it is a string, with the value passed on cmdline. 
My problem is fixed with following patch:

--- /home/tdescham/repo/contrib/kallithea/venv/kallithea-stable/lib/python3.6/site-packages/isort/main.py.orig	2020-03-07 21:10:12.517836807 +0100
+++ /home/tdescham/repo/contrib/kallithea/venv/kallithea-stable/lib/python3.6/site-packages/isort/main.py	2020-03-07 21:10:15.674836678 +0100
@@ -285,7 +285,7 @@
                         help='Returns just the current version number without the logo')
     parser.add_argument('-w', '--line-width', help='The max length of an import line (used for wrapping long imports).',
                         dest='line_length', type=int)
-    parser.add_argument('-wl', '--wrap-length', dest='wrap_length',
+    parser.add_argument('-wl', '--wrap-length', dest='wrap_length', type=int,
                         help="Specifies how long lines that are wrapped should be, if not set line_length is used.")
     parser.add_argument('-ws', '--ignore-whitespace', action='store_true', dest="ignore_whitespace",
                         help='Tells isort to ignore whitespace differences when --check-only is being used.')
